# -*- coding: utf-8 -*-
"""G6 RAG Project Final Version for Hugging Face  (without ics export)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/111KKcMi-mpkFemP3wvBTNmCXF4ik-82k
"""

import gradio as gr
import pandas as pd
import tempfile
import re

from pymongo import MongoClient
from langchain_openai import ChatOpenAI

from fpdf import FPDF
from ics import Calendar, Event
import os

from langchain_openai import OpenAIEmbeddings
from langchain_core.documents import Document

# Initialize variables
openai_api_key = None
mongo_uri = None

# Environment Variables (Hugging Face Secrets)
if not openai_api_key:
    openai_api_key = os.environ.get("OPENAI_API_KEY")
if not mongo_uri:
    mongo_uri = os.environ.get("MONGO_URI")

# Set the environment variable for libraries that look for it automatically
if openai_api_key:
    os.environ["OPENAI_API_KEY"] = openai_api_key
else:
    print("⚠️ Warning: OPENAI_API_KEY not found!")

if not mongo_uri:
    print("⚠️ Warning: MONGO_URI not found!")

client = MongoClient(mongo_uri)

db = client["ici"]
collection = db["Group6 Final Proj"]

data = list(collection.find())

df = pd.DataFrame(data)

print("Number of documents loaded:", len(df))

df.head()

# Convert DataFrame rows to LangChain Document objects
docs = []
for index, row in df.iterrows():
    docs.append(Document(page_content=row['text'], metadata={'filename': row['filename']}))

pdf_files = [
    "ZU1946001 - Sheet1.pdf",
    "ZU1919001 - Sheet1.pdf",
    "ZU1902001 - Sheet1.pdf",
    "ZU1887001 - Sheet1.pdf",
    "ZU1884001 - Sheet1.pdf",
    "ZU1883001 - Sheet1.pdf",
    "ZU1867001 - Sheet1.pdf",
    "ZU1866001 - 工作表1.pdf",
    "ZU1864001 - Sheet1.pdf",
    "ZU1863001 - Sheet1.pdf",
    "ZU1855001 - Sheet1.pdf",
    "ZU1854001 - Sheet1.pdf",
    "ZU1852001 - Sheet1.pdf",
    "ZU1047001 - Sheet1.pdf",
    "ZU1046001 - Sheet1.pdf",
    "ZU1045001 - 工作表1.pdf",
    "ZU1043001 - 工作表1.pdf",
    "ZU1028001 - Sheet1.pdf",
    "ZU1023001 - 工作表1.pdf",
    "ZU1017001 - 工作表1.pdf",
    "ZU1012001 - Sheet1.pdf",
    "ZU1008001 - Sheet1.pdf",
    "ZU1006001 - Sheet1.pdf",
    "ZU1005011 - Sheet1.pdf",
    "ZU1853001 - Sheet1.pdf"
]

course_mapping = {
    "ZU1853001 Reimagining the World: The Politics and Art of Social Change": "ZU1853001 - Sheet1.pdf",
    "ZU1005011 Public International Law": "ZU1005011 - Sheet1.pdf",
    "ZU1006001 Migration and Globalization": "ZU1006001 - Sheet1.pdf",
    "ZU1008001 Anthropocene and Geopolitics": "ZU1008001 - Sheet1.pdf",
    "ZU1012001 Research Methods": "ZU1012001 - Sheet1.pdf",
    "ZU1017001 Introduction to AI": "ZU1017001 - 工作表1.pdf",
    "ZU1023001 Human Geography": "ZU1023001 - 工作表1.pdf",
    "ZU1028001 International Innovation Management": "ZU1028001 - Sheet1.pdf",
    "ZU1043001 Public Administration": "ZU1043001 - 工作表1.pdf",
    "ZU1045001 Global Issues in Asia": "ZU1045001 - 工作表1.pdf",
    "ZU1046001 AI & Governance": "ZU1046001 - Sheet1.pdf",
    "ZU1047001 Big Data for Social Analysis": "ZU1047001 - Sheet1.pdf",
    "ZU1852001 Advanced International Law Seminar": "ZU1852001 - Sheet1.pdf",
    "ZU1854001 International Courts and Tribunals: Rules and Orders": "ZU1854001 - Sheet1.pdf",
    "ZU1855001 Open Data and Open Government": "ZU1855001 - Sheet1.pdf",
    "ZU1863001 Intersection of International Business and National Security: Export Controls, Sanctions, Foreign Direct Investments, and Supply Chain": "ZU1863001 - Sheet1.pdf",
    "ZU1864001 Global Environment in Social Theory: Economics, Politics, and Ecology": "ZU1864001 - Sheet1.pdf",
    "ZU1866001 Digital Humanities and Artificial Intelligence": "ZU1866001 - 工作表1.pdf",
    "ZU1867001 Data Science Fundamentals for the Social Sciences": "ZU1867001 - Sheet1.pdf",
    "ZU1883001 Capstone: Generative AI": "ZU1883001 - Sheet1.pdf",
    "ZU1884001 US Patent Law and Practice": "ZU1884001 - Sheet1.pdf",
    "ZU1887001 Religion and Politics in the Modern World": "ZU1887001 - Sheet1.pdf",
    "ZU1902001 Political Economy of East Asia": "ZU1902001 - Sheet1.pdf",
    "ZU1919001 Capstone: Design for Social Innovation": "ZU1919001 - Sheet1.pdf",
    "ZU1946001 Comparative Government and Politics": "ZU1946001 - Sheet1.pdf"
}

# =========================================================
# LLM
# =========================================================

llm = ChatOpenAI(
    model_name="gpt-4.1-mini",
    temperature=0,
    max_tokens=3000
)

# =========================================================
# GLOBAL DATAFRAME
# =========================================================

current_df = pd.DataFrame(
    columns=["Week", "Course", "Type", "Task"]
)

# =========================================================
# SORT FUNCTION
# =========================================================

def sort_df(df):

    try:
        df["Week"] = pd.to_numeric(df["Week"])
    except:
        pass

    df = df.sort_values(by="Week")

    return df.reset_index(drop=True)

# =========================================================
# STRESS CALCULATION
# =========================================================

def calculate_stress_levels(df):

    week_scores = {}

    for week in range(1, 17):

        week_df = df[df["Week"] == week]

        score = 0

        for _, row in week_df.iterrows():

            if row["Type"] == "Exam":
                score += 3

            elif row["Type"] == "Assignment":
                score += 1

        week_scores[week] = score

    return week_scores

# =========================================================
# HTML DISPLAY
# =========================================================

def dataframe_to_html(df):

    if df.empty:
        return "<h3>No tasks for now :)</h3>"

    df = sort_df(df)

    stress_scores = calculate_stress_levels(df)

    html = ""

    for week in range(1, 17):

        week_df = df[df["Week"] == week]

        if week_df.empty:
            continue

        score = stress_scores[week]

        # Stress colours
        if score < 3:
            bg = "#ffffff"

        elif score < 6:
            bg = "#ffe5e5"

        elif score < 9:
            bg = "#ffb3b3"

        else:
            bg = "#ff6666"

        html += f"""
        <div style="
            margin-top:25px;
            padding:20px;
            border-radius:15px;
            background-color:{bg};
        ">
        """

        html += f"""
        <h2 style="
          color:#222222;
          margin-bottom:10px;
        ">
        Week {week}
        </h2>
        <p style="color: #000000 !important; margin-top: 0; margin-bottom: 15px;">
            <b style="color: #000000 !important;">Stress Score:</b> {score}
        </p>
        """

        html += """
        <table style="
            width:100%;
            border-collapse:collapse;
            border-color:#222222;
        ">
        """

        html += """
        <tr style="background-color:#222222">
            <th style="padding:10px;">Course</th>
            <th style="padding:10px;">Type</th>
            <th style="padding:10px;">Task</th>
        </tr>
        """

        for _, row in week_df.iterrows():

            html += f"""
            <tr style="background-color:#222222">
                <td style="padding:10px;">{row['Course']}</td>
                <td style="padding:10px;">{row['Type']}</td>
                <td style="padding:10px;">{row['Task']}</td>
            </tr>
            """

        html += "</table></div>"

    return html

# =========================================================
# GENERATE SCHEDULE
# =========================================================

def generate_schedule(selected_courses):

    global current_df

    if not selected_courses:
        return "<h3>Please select courses.</h3>", current_df

    combined_text = ""

    for course_name in selected_courses:

        filename = course_mapping[course_name]

        result = collection.find_one({"filename": filename})

        if result:

            combined_text += f"\n\nCOURSE FILE: {course_name}\n"
            combined_text += result["text"]

    prompt = f"""
You are a university schedule assistant.

TASK:
Extract ALL assignments,readings and exams from the syllabus text.

RULES:
- Output ONLY CSV rows
- One row = one task
- Use ONLY these task types:
    - Assignment
    - Exam
- Weeks must be integers from 1-16

CSV FORMAT:

Week,Course,Type,Task

EXAMPLE:

5,Statistics II,Assignment,Homework 3
5,Sociology,Exam,Midterm

Syllabus text:
{combined_text}
"""

    response = llm.invoke(prompt)

    output = response.content.strip()

    rows = []

    for line in output.split("\n"):

        parts = line.split(",")

        if len(parts) >= 4:

            week = parts[0].strip()
            course = parts[1].strip()
            task_type = parts[2].strip()
            task = ",".join(parts[3:]).strip()

            # Restrict task types
            if task_type not in ["Assignment", "Exam"]:
                continue

            rows.append([
                int(week),
                course,
                task_type,
                task
            ])

    current_df = pd.DataFrame(
        rows,
        columns=["Week", "Course", "Type", "Task"]
    )

    current_df = sort_df(current_df)

    return dataframe_to_html(current_df), current_df

# =========================================================
# ADD TASK
# =========================================================

def add_task(df):

    new_row = pd.DataFrame(
        [[1, "", "Assignment", ""]],
        columns=["Week", "Course", "Type", "Task"]
    )

    updated_df = pd.concat([df, new_row], ignore_index=True)

    return updated_df

# =========================================================
# CONFIRM TASKS
# =========================================================

def confirm_tasks(df):

    global current_df

    df = sort_df(df)

    current_df = df

    return dataframe_to_html(current_df), current_df

# =========================================================
# DELETE LAST TASK
# =========================================================

def delete_last_task(df):

    global current_df

    if len(df) > 0:
        df = df.iloc[:-1]

    df = sort_df(df)

    current_df = df

    return dataframe_to_html(current_df), current_df

# =========================================================
# EXPORT FUNCTION
# =========================================================

def export_schedule(df, export_type):

    if df.empty:
        return None

    # ---------------- PDF ----------------

    if export_type == "PDF":

        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.set_font("Arial", size=12)

        for _, row in df.iterrows():

            line = (
                f"Week {row['Week']} | "
                f"{row['Course']} | "
                f"{row['Type']} | "
                f"{row['Task']}"
            )

            # Remove unsupported unicode
            line = line.encode("latin-1", "ignore").decode("latin-1")

            pdf.multi_cell(0, 10, line)

        path = tempfile.NamedTemporaryFile(
            delete=False,
            suffix=".pdf"
        ).name

        pdf.output(path)

        return path

    # ---------------- CSV ----------------

    elif export_type == "CSV":

        path = tempfile.NamedTemporaryFile(
            delete=False,
            suffix=".csv"
        ).name

        df.to_csv(path, index=False)

        return path

# =========================================================
# UI
# =========================================================

with gr.Blocks(theme=gr.Theme.from_hub("hmb/midnight")) as demo:

    gr.Markdown("# Syllabuddy")
    gr.Markdown("The Ultimate NCCU Student Survival Guide")

    # =====================================================
    # COURSE SELECTION
    # =====================================================

    course_selector = gr.CheckboxGroup(
    choices=list(course_mapping.keys()),
    label="Select Courses"
)

    generate_button = gr.Button("Generate Schedule")

    # =====================================================
    # HTML SCHEDULE DISPLAY
    # =====================================================

    schedule_html = gr.HTML()

    # =====================================================
    # EDITABLE TABLE
    # =====================================================

    gr.Markdown("## Edit Tasks")

    schedule_table = gr.Dataframe(
        headers=["Week", "Course", "Type", "Task"],
        datatype=["number", "str", "str", "str"],
        interactive=True,
        row_count=(1, "dynamic"),
        col_count=(4, "fixed")
    )

    # =====================================================
    # BUTTONS
    # =====================================================

    with gr.Row():

        add_button = gr.Button("Add Task")

        confirm_button = gr.Button("Confirm Changes")

        delete_button = gr.Button("Delete Last Task")

    # =====================================================
    # EXPORT
    # =====================================================

    gr.Markdown("## Export Schedule")

    export_dropdown = gr.Dropdown(
        choices=["PDF", "CSV"],
        label="Export Format"
    )

    export_button = gr.Button("Export")

    download_output = gr.File()

    # =====================================================
    # BUTTON CONNECTIONS
    # =====================================================

    generate_button.click(
        fn=generate_schedule,
        inputs=course_selector,
        outputs=[schedule_html, schedule_table]
    )

    add_button.click(
        fn=add_task,
        inputs=schedule_table,
        outputs=schedule_table
    )

    confirm_button.click(
        fn=confirm_tasks,
        inputs=schedule_table,
        outputs=[schedule_html, schedule_table]
    )

    delete_button.click(
        fn=delete_last_task,
        inputs=schedule_table,
        outputs=[schedule_html, schedule_table]
    )

    export_button.click(
        fn=export_schedule,
        inputs=[schedule_table, export_dropdown],
        outputs=download_output
    )

# =========================================================
# LAUNCH
# =========================================================

demo.launch(server_name="0.0.0.0", server_port=7860)
